export enum QueryKeys {
  CONTENT = "CONTENT",
  CONTENTDETAIL = "CONTENTDETAIL",
  CHILDCONTENT = "CHILDCONTENT",
  CHILDCONTENTDETAIL = "CHILDCONTENTDETAIL",
  ALBUMS = "ALBUMS",
  ALBUMDETAIL = "ALBUMDETAIL",
  ALBUMPHOTOS = "ALBUMPHOTOS",
}
